---
name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Run nox
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5.1.0
      - name: Install dependencies
        run: uv sync
      - name: Run nox
        run: uv run nox -s lint_check slots mypy cov
